### ISSUE TITLE
Center text in a toast message?

### ISSUE THREAD

**Issue by DukeGamma** [krishKM/Modern-UI-Components-for-VBA#41]
Is it possible to center text and change any other formatting?

**Comment by Saphirah** [comment]
I would be interested in this too. Right now the text looks weird, when it is bound to the top left. I would like to be able to set a margin or center the text. Can we use standart html inside the MessageBox?

Edit: Tested it and html does not work.

**Comment by lajjutz** [comment]
Hello
In my case I usually put more space characters, in order to get an center text, but, when the text length is major than 34 a new line is created..

![image](https://user-images.githubusercontent.com/44538069/96153424-ebf7cb80-0eca-11eb-84bf-c9368ecda20d.png)

![image](https://user-images.githubusercontent.com/44538069/96159720-3af52f00-0ed2-11eb-904e-fd7f875de955.png)

Regards.

**Comment by krishKM** [comment]
Fixed, update relased. 
You can now use TextAlign, PaddingLeft, MarginLeft properties. See the sample file

**Comment by lajjutz** [comment]
Hello Krish..

How we use these properties when calling the object gDll.Toast?
